[workspace]
resolver = "2"

members = [
    "chapter1_empty_window",
    "chapter2_background",
    "chapter3_triangle",
    "chapter4_coloured_triangle",
    "chapter5_rotating_triangle",
    "chapter6_rotating_triangle_3d",
    "chapter6_rotating_triangle_3d_glam",

]
